language: rust
os:
  - linux
  - osx

rust:
  - nightly

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri); fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-apple-darwin/miri); fi

script:
  - rustup set profile minimal
  - rustup default "$MIRI_NIGHTLY"
  - rustup component add miri
  - yes | cargo miri test --features="std"
  - cargo test --no-default-features
  - cargo bench
