language: rust
os: linux
cache: cargo

rust:
  - nightly

script:
  # miri is temporarily disabled until it stops
  # icing on the new `symmetric_difference` function
  # - bash ./ci/run_miri.sh
  - cargo test
  - cargo test --no-default-features
  - cargo bench
