language: rust

rust:
  - nightly

script:
  - cargo build -j16
  - cargo test -j16 --features="std"
  - cargo bench -j16
  - cargo clean
  - rustup component add miri
  - cargo miri -j16 setup
  - cargo miri -j16 test --features="std"