language: rust
cache: cargo

rust:
  - nightly

script:
  - rustup component add miri
  - cargo miri test --verbose --features="std"
  - cargo test -j16 --verbose --features="std"
  - cargo bench -j16