language: rust
cache: cargo

rust:
  - nightly

script:
  - cargo build -j16
  - cargo test -j16 --feature="std"
  - cargo bench -j16
  - rustup component add miri
  - cargo miri setup
  - cargo miri test --feature="std"