language: rust

rust:
  - nightly

jobs:
  include:
  - os: linux
    dist: bionic
  - os: osx

script:
  # Miri is temporarily disabled until it supports `const_loop`.
  # - bash ./ci/run_miri.sh
  - cargo test --features="std"
  - cargo test --no-default-features
