skip_tags: true
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      channel: nightly
      target: x86_64-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      channel: nightly
      target: x86_64-pc-windows-gnu
      bits: 64
      msys2: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      channel: nightly
      target: x86_64-unknown-linux-gnu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      channel: nightly
      target: x86_64-apple-darwin
branches:
  only:
    - master
install:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019 Preview"
      (appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe &&
       rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal)
    else
      (appveyor DownloadFile https://sh.rustup.rs/ -FileName rustup-init.sh &&
       bash rustup-init.sh -yv --default-toolchain %channel% --default-host %target% --profile minimal)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019 Preview"
      set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    else
      export PATH=$PATH:~%USERPROFILE%/.cargo/bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup update --force
  - rustc -vV
  - cargo -vV
cache:
  - '%USERPROFILE%/.cargo'
build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%
