image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
branches:
  only:
    - master
install:
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 cmd: set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup toolchain uninstall %channel%-%target%
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal
  - rustup update --force
cache:
  - '%USERPROFILE%\.cargo'
build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%