image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    channel: nightly
    target: x86_64-pc-windows-msvc
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup update --force
cache:
  - '%USERPROFILE%\.cargo'
image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    channel: nightly
    target: x86_64-pc-windows-msvc
    bits: 64
    msys2: 1
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal
  - set PATH=%USERPROFILE%\.cargo\bin;C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup update --force
cache:
  - '%USERPROFILE%\.cargo'

build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%
