image:
  - Visual Studio 2019 Preview
  - Ubuntu2004
  - macOS
skip_tags: true
branches:
  only:
    - master
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019 Preview
    environment:
      matrix:
        - channel: nightly
          target: x86_64-pc-windows-msvc
        - channel: nightly
          target: i686-pc-windows-msvc
    install:
      - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      - cmd: rustup-init -yv --default-toolchain nightly --default-host %target% --profile minimal
      - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    cache:
      - '%USERPROFILE%\.cargo'
  -
    matrix:
      only:
        - image: Ubuntu2004
    environment:
      channel: nightly
      target: x86_64-unknown-linux-gnu
    install:
      - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -yv --default-toolchain nightly --default-host $target --profile minimal
      - sh: export PATH=$PATH:/$HOME/.cargo/bin
    cache:
      - '$HOME/.cargo'
  -
    matrix:
      only:
        - image: macOS
    environment:
      channel: nightly
      target: x86_64-apple-darwin
    install:
      - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -yv --default-toolchain nightly --default-host $target --profile minimal
      - sh: export PATH=$PATH:/$HOME/.cargo/bin
    cache:
      - '$HOME/.cargo'
build: false
test_script:
  # We run the suite once with all functionality enabled, and then once without
  # the default features to make sure `no_std` support has not been broken
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
