image: Visual Studio 2019
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-gnu
      bits: 64
      msys2: 1
branches:
  only:
    - master
install:
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 cmd: set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup toolchain uninstall %channel%-%target%
  - rustup toolchain install %channel%-%target%
  - rustup update --force
  - rustc -vV
  - cargo -vV
cache:
  - '%USERPROFILE%\.cargo'
build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%
