image:
  - Visual Studio 2019 Preview
  - Ubuntu2004
  - macOS
environment
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc
matrix:
  exclude:
    - image: Ubuntu2004
      TARGET: x86_64-pc-windows-msvc
    - image: Ubuntu2004
      TARGET: i686-pc-windows-msvc
    - image: macOS
      TARGET: x86_64-pc-windows-msvc
    - image: macOS
      TARGET: i686-pc-windows-msvc
skip_tags: true
branches:
  only:
    - master
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019 Preview
    install:
      - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      - cmd: rustup-init.exe -yv --default-toolchain nightly --default-host %TARGET% --profile minimal
      - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    cache:
      - '%USERPROFILE%\.cargo'
  -
    matrix:
      only:
        - image: Ubuntu2004
    install:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -yv --default-toolchain nightly --default-host x86_64-unknown-linux-gnu --profile minimal
      - sh: export PATH=$PATH:/$HOME/.cargo/bin
    cache:
      - '$HOME/.cargo'
  -
    matrix:
      only:
        - image: macOS
    install:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -yv --default-toolchain nightly --default-host x86_64-apple-darwin --profile minimal
      - sh: export PATH=$PATH:/$HOME/.cargo/bin
    cache:
      - '$HOME/.cargo'
build: false
test_script:
  # We run the suite once with all functionality enabled, and then once without
  # the default features to make sure `no_std` support has not been broken
  - ps: ./ci/run_windows.ps1
  - sh: ./ci/run_linux_and_mac.sh