image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
branches:
  only:
    - master
install:
  - cmd: mkdir C:\Users\appveyor\rust
  - cmd: mkdir C:\Users\appveyor\rust\bin
  - cmd: set CARGO_HOME=C:\Users\appveyor\rust && set RUSTUP_HOME=C:\Users\appveyor\rust && set RUST_SYSROOT=C:\Users\appveyor\rust && set PATH=%PATH%;C:\Users\appveyor\rust\bin
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe && rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal
  - rustup update --force
cache:
  - 'C:\Users\appveyor\rust'
build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%
