image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-gnu
      bits: 64
      msys2: 1
branches:
  only:
    - master
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 cmd: set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup component remove clippy
  - rustup component remove rustfmt
  - rustup component remove rust-docs
  - rustup component remove rust-src
  - rustup update --force
  - rustc -vV
  - cargo -vV
cache:
  - '%USERPROFILE%\.cargo'
build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%
