image:
  - Visual Studio 2019 Preview
  - Ubuntu2004
  - macOS
skip_tags: true
branches:
  only:
    - master
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019 Preview
    environment:
      matrix:
        - TARGET: x86_64-pc-windows-msvc
        - TARGET: i686-pc-windows-msvc
    install:
      - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      - ps: rustup-init -yv --default-toolchain nightly --default-host $env:TARGET --profile minimal
      - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    cache:
      - '%USERPROFILE%\.cargo'
  -
    matrix:
      only:
        - image: Ubuntu2004
    install:
      - appveyor DownloadFile https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init -FileName rustup-init
      - sh: ./rustup-init -yv --default-toolchain nightly --default-host x86_64-unknown-linux-gnu --profile minimal
      - sh: export PATH=$PATH:/$HOME/.cargo/bin
    cache:
      - '$HOME/.cargo'
  -
    matrix:
      only:
        - image: macOS
    install:
      - appveyor DownloadFile https://static.rust-lang.org/rustup/dist/x86_64-apple-darwin/rustup-init -FileName rustup-init
      - sh: ./rustup-init -yv --default-toolchain nightly --default-host x86_64-apple-darwin --profile minimal
      - sh: export PATH=$PATH:/$HOME/.cargo/bin
    cache:
      - '$HOME/.cargo'
build: false
test_script:
  # We run the suite once with all functionality enabled, and then once without
  # the default features to make sure `no_std` support has not been broken
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
