image: Visual Studio 2019 Preview
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-gnu
      bits: 64
      msys2: 1
branches:
  only:
    - master
install:
  - cmd: set CARGO_HOME=C:\Users\appveyor\rust && set RUSTUP_HOME=C:\Users\appveyor\rust && set RUST_SYSROOT=C:\Users\appveyor\rust && set PATH=%PATH%;C:\Users\appveyor\rust\bin
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe && rustup-init -yv --default-toolchain %channel% --default-host %target% --profile minimal
  - rustup update --force
  - if defined MSYS2 cmd: set PATH=%PATH%;C:\msys64\mingw%BITS%\bin
cache:
  - 'C:\Users\appveyor\rust'
build: false
test_script:
  - cargo test --features="std" --target=%target%
  - cargo test --no-default-features --target=%target%
  - cargo bench --target=%target%
