image: Visual Studio 2019
skip_tags: true
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-gnu
      bits: 64
      msys2: 1
branches:
  only:
    - master
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 cmd: set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustup update
  - rustc -vV
  - cargo -vV
cache:
  - '%USERPROFILE%\.cargo'
test_script:
  - cargo test --features="std"
  - cargo test --no-default-features
  - cargo bench
