[package]
name = "staticvec"
description = "Implements a fixed-capacity stack-allocated Vec alternative backed by an array, using const generics."
homepage = "https://crates.io/crates/staticvec"
repository = "https://github.com/slightlyoutofphase/staticvec"
license = "MIT OR Apache-2.0"
readme = "README.md"
version = "0.2.75"
authors = ["SlightlyOutOfPhase <slightlyoutofphase@gmail.com>"]
keywords = ["vec","array","container","vector","stack"]
categories = ["data-structures"]
edition = "2018"
include = ["Cargo.toml", "rustfmt.toml", "src/**/*.rs", "demo/**/*.rs", "benchmark/**/*.rs", "test/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]

[lib]
doctest = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.test]
incremental = false

[[bench]]
name = "benchmark"
path = "benchmark/benchmark.rs"

[[example]]
name = "demo"
path = "demo/demo.rs"

[[test]]
name = "test"
path = "test/test.rs"

[features]
std = []
default = ["std"]

[dependencies]
